apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka3-logs
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka3
  labels:
    node: kafka3
    cluster: kafka
spec:
  containers:
    - image: wurstmeister/kafka:0.10.1.1
      name: kafka

      ports:
        - containerPort: 9092
          name: client

      env:
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka3
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka.zookeeper.connect
        - name: KAFKA_LOG_DIRS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka.log.dirs

      volumeMounts:
        - name: logs
          mountPath: /kafka

  volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: kafka3-logs
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
spec:
  selector:
    node: kafka3
  clusterIP: None
  ports:
    - port: 9092
      name: client
